name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3

      - name: Build Application
        run: |
          mkdir -p bin
          for dir in $(find src -maxdepth 1 -type d -not -path src); do
            app=$(basename $dir)
            GOOS=windows GOARCH=amd64 go build -o bin/${app}.exe $dir/main.go
          done

      - name: Archive build output
        run: |
          cd bin
          zip -r ltfw-windows-amd64.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ltfw-windows-amd64
          path: bin/ltfw-windows-amd64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./bin

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ltfw-windows-amd64/ltfw-windows-amd64.zip
          asset_name: ltfw-windows-amd64.zip
          asset_content_type: application/zip
