name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Install gocovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Display Environment Information
        run: go env

      - name: List Contents for Debugging
        run: |
          echo "Root Directory Contents:"
          ls -la
          echo "Source Directory Contents:"
          ls -la src

      - name: Install dependencies and run tests
        run: |
          mkdir -p coverage
          cwd=${{ github.workspace }}

          for dir in src/*; do
            if [ -d "$dir" ]; then
              echo "Processing directory: $dir"
              cd $dir

              if [ -f "go.mod" ]; then
                go mod tidy
                go mod download
              fi

              if ls *_test.go 1> /dev/null 2>&1; then
                go test -v -covermode=atomic -coverprofile=$cwd/coverage/$(basename $dir).out ./...
              else
                echo "No test files found in $dir"
              fi

              cd $cwd
            fi
          done

      - name: Merge coverage files
        run: |
          gocovmerge coverage/*.out > coverage/cover.out

      - name: Adjust coverage paths
        run: |
          # Create a temp file for adjusted output
          TEMP_COVER_OUT=$(mktemp)
          echo "mode: set" > $TEMP_COVER_OUT

          # Adjust paths to be relative in the coverage file 
          sed 's#/home/runner/work/cli-tools-for-windows/cli-tools-for-windows/##g' coverage/cover.out | grep -v "^mode:" >> $TEMP_COVER_OUT

          mv $TEMP_COVER_OUT coverage/cover.out

      - name: Show Merged Coverage File
        run: |
          echo "Merged coverage file content:"
          cat coverage/cover.out

      - name: Install Coveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Upload Coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: goveralls -coverprofile=coverage/cover.out -service=github
