name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4

      - name: Run Tests
        run: |
          mkdir -p coverage
          cwd=${{ github.workspace }}
          for dir in src/*; do
            if [ -f "$dir/go.mod" ] || ls $dir/*_test.go 1> /dev/null 2>&1; then
              app=$(basename $dir)
              cd $dir
              go test -coverprofile=$cwd/coverage/${app}.out ./...
              cd $cwd
            fi
          done
          # Merge individual coverage files
          echo "mode: set" > coverage/cover.out
          find coverage -name '*.out' | grep -v "cover.out" | xargs grep -h -v "^mode:" >> coverage/cover.out

      - name: Print Coverage Directory
        run: ls -la coverage

      - name: Print Individual Coverage Files
        run: cat coverage/*.out

      - name: Print Merged Coverage File
        run: cat coverage/cover.out

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: coverage/cover.out
