name: Test and Coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4
      - name: Install dependencies and run tests
        run: |
          mkdir -p coverage
          cwd=${{ github.workspace }}
          for dir in src/*; do
            if [ -f "$dir/go.mod" ] || ls $dir/*_test.go 1> /dev/null 2>&1; then
              app=$(basename $dir)
              cd $dir
              go mod download
              go test -covermode=atomic -coverprofile=$cwd/coverage/${app}.out ./...
              cd $cwd
            fi
          done
          # Merge individual coverage files
          echo "mode: atomic" > coverage/cover.out
          find coverage -name '*.out' | grep -v "cover.out" | xargs grep -h -v "^mode:" >> coverage/cover.out
      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send Coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: goveralls -coverprofile=coverage/cover.out -service=github
